import { useState } from 'react'
import type { AnalyzeResponse, TestCase } from '../types'

export function DashboardView({ result, testCases, executionStatuses = {} }: { result: AnalyzeResponse; testCases: TestCase[]; executionStatuses?: Record<string, 'passed' | 'failed' | 'pending'> }) {
  const [customizeOpen, setCustomizeOpen] = useState(false)
  const [visible, setVisible] = useState({ status: true, priority: true, type: true, automation: true })
  const execution = { passed: testCases.filter((item) => executionStatuses[item.id] === 'passed').length, failed: testCases.filter((item) => executionStatuses[item.id] === 'failed').length, pending: testCases.filter((item) => executionStatuses[item.id] !== 'passed' && executionStatuses[item.id] !== 'failed').length }
  const priorities = countBy(testCases, (item) => item.priority)
  const types = countBy(testCases, (item) => item.type)
  const automation = countBy(testCases, (item) => item.automationStatus)
  const max = Math.max(...Object.values(priorities), 1)
  const toggle = (key: keyof typeof visible) => setVisible((current) => ({ ...current, [key]: !current[key] }))
  return <div className="dashboard-view">
    <div className="dashboard-title"><div><p className="eyebrow">Project dashboard</p><h2>Quality overview</h2><p>Coverage and readiness for <b>{result.origin}</b></p></div><div className="dashboard-actions"><span className="status-badge status-badge-warn">{execution.pending} pending execution</span><button type="button" className="btn btn-secondary" onClick={() => setCustomizeOpen((current) => !current)}>⚙ Customize</button><button type="button" className="btn btn-primary" onClick={() => window.print()}>⇩ Export PDF</button></div></div>
    {customizeOpen && <div className="dashboard-customize"><b>Dashboard layout</b><span>Select panels</span>{(['status', 'priority', 'type', 'automation'] as const).map((key) => <label key={key}><input type="checkbox" checked={visible[key]} onChange={() => toggle(key)} /> {key === 'status' ? 'Execution status' : key === 'priority' ? 'Priority' : key === 'type' ? 'Test type' : 'Automation readiness'}</label>)}</div>}
    <div className="dashboard-metrics"><Metric label="Test Cases" value={testCases.length} hint={`${result.pages.length} pages explored`} tone="blue" /><Metric label="Pass" value={execution.passed} hint="Execution result" tone="green" /><Metric label="Failed" value={execution.failed} hint="Execution result" tone="red" /><Metric label="Need Review" value={automation['needs-review'] ?? 0} hint="Tester decision needed" tone="amber" /></div>
    <div className="dashboard-columns">{visible.status && <section className="dashboard-card"><div className="dashboard-card-head"><div><p className="eyebrow">Execution status</p><h3>Test Case progress</h3></div><span className="muted">Run not started</span></div><div className="status-chart"><StatusBar label="Passed" value={execution.passed} total={testCases.length} color="green" /><StatusBar label="Failed" value={execution.failed} total={testCases.length} color="red" /><StatusBar label="Pending" value={execution.pending} total={testCases.length} color="amber" /></div><div className="legend"><span><i className="dot-green" /> Pass {execution.passed}</span><span><i className="dot-red" /> Failed {execution.failed}</span><span><i className="dot-amber" /> Pending {execution.pending}</span></div></section>}{visible.priority && <section className="dashboard-card"><div className="dashboard-card-head"><div><p className="eyebrow">Distribution</p><h3>Priority</h3></div><span className="muted">All cases</span></div><div className="bar-chart">{(['high', 'medium', 'low'] as const).map((key) => <div className="bar-row" key={key}><span>{key}</span><div><i style={{ width: `${(priorities[key] / max) * 100}%` }} /></div><b>{priorities[key] ?? 0}</b></div>)}</div></section>}</div>
    <div className="dashboard-columns">{visible.type && <section className="dashboard-card"><div className="dashboard-card-head"><div><p className="eyebrow">Coverage</p><h3>Test type</h3></div></div><div className="mini-grid">{Object.entries(types).map(([key, value]) => <div className="mini-stat" key={key}><b>{value}</b><span>{key}</span></div>)}</div></section>}{visible.automation && <section className="dashboard-card"><div className="dashboard-card-head"><div><p className="eyebrow">Automation</p><h3>Readiness</h3></div></div><div className="readiness-list">{[['ready', 'Ready for automation'], ['needs-review', 'Needs review'], ['needs-data', 'Needs test data'], ['manual', 'Manual only']].map(([key, label]) => <div key={key}><span>{label}</span><b>{automation[key] ?? 0}</b></div>)}</div></section>}</div>
  </div>
}
function countBy(items: TestCase[], key: (item: TestCase) => string) { return items.reduce<Record<string, number>>((counts, item) => { const value = key(item); counts[value] = (counts[value] ?? 0) + 1; return counts }, {}) }
function Metric({ label, value, hint, tone }: { label: string; value: number; hint: string; tone: string }) { return <div className={`dashboard-metric tone-${tone}`}><span>{label}</span><strong>{value}</strong><small>{hint}</small></div> }
function StatusBar({ label, value, total, color }: { label: string; value: number; total: number; color: string }) { return <div className="status-row"><span>{label}</span><div><i className={`fill-${color}`} style={{ width: `${total ? (value / total) * 100 : 0}%` }} /></div><b>{value}</b></div> }
